#!/usr/bin/env python3
"""
Convert LLM-generated Markdown test descriptions into executable pytest files.

This script reads Markdown test case files from data/generated_test_cases
and creates pytest files under tests/generated_pdf_tests.

The generated tests currently validate that each Markdown input is usable
and prepare a placeholder PDF output file. In the final integration, this
placeholder step can be replaced with the real Markdown2Pdf.Console call.
"""

import re
from pathlib import Path


class MarkdownToPdfTestConverter:
    def __init__(self) -> None:
        self.markdown_dir = Path("data/generated_test_cases")
        self.output_dir = Path("tests/generated_pdf_tests")
        self.pdf_output_dir = Path("data/generated_pdfs")

        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.pdf_output_dir.mkdir(parents=True, exist_ok=True)

    def sanitize_test_name(self, name: str) -> str:
        """Convert a test case title into a valid Python test name."""
        clean_name = re.sub(r"[^\w\s-]", "", name)
        clean_name = clean_name.strip().lower()
        clean_name = clean_name.replace(" ", "_").replace("-", "_")
        clean_name = re.sub(r"_+", "_", clean_name)
        clean_name = clean_name[:40].strip("_")

        return clean_name or "generated_case"

    def parse_markdown_tests(self, markdown_content: str) -> list[dict]:
        """Extract test cases from a Markdown file generated by the LLM."""
        tests = []

        test_blocks = re.split(r"## Test Case \d+:", markdown_content)

        for index, block in enumerate(test_blocks[1:], start=1):
            lines = block.strip().splitlines()
            test_name = lines[0].strip() if lines else f"Generated Test Case {index}"

            markdown_match = re.search(
                r"### Input:\s*```markdown\s*(.*?)\s*```",
                block,
                re.DOTALL | re.IGNORECASE,
            )

            if not markdown_match:
                print(f"  Skipped test {index}: no Markdown input block found")
                continue

            markdown_input = markdown_match.group(1).strip()

            content_without_symbols = re.sub(r"[-_\s]", "", markdown_input)

            if len(content_without_symbols) < 10:
                print(f"  Skipped test {index}: Markdown input is too short")
                continue

            tests.append(
                {
                    "name": test_name,
                    "markdown": markdown_input,
                    "expected": [],
                    "sanitized_name": self.sanitize_test_name(test_name),
                }
            )

        return tests

    def generate_pytest_file(self, tests: list[dict], source_name: str) -> str:
        """Create the Python pytest file content."""
        pytest_code = f'''#!/usr/bin/env python3
"""
Generated PDF tests from Markdown test cases: {source_name}

These tests were generated from LLM-produced Markdown test descriptions.
They check that each generated Markdown input is non-empty and can be prepared
for the PDF conversion workflow.
"""

from pathlib import Path


class TestGeneratedPdfCases:
    def setup_method(self):
        self.pdf_dir = Path("data/generated_pdfs")
        self.pdf_dir.mkdir(parents=True, exist_ok=True)
'''

        for index, test in enumerate(tests, start=1):
            test_name = test["sanitized_name"]
            readable_name = test["name"]
            markdown_input = test["markdown"]
            expected_elements = test["expected"]

            pytest_code += f'''
    def test_pdf_generation_{index}_{test_name}(self):
        """Test Case: {readable_name}"""
        test_id = {index}
        test_name = {readable_name!r}
        markdown_input = {markdown_input!r}
        expected_elements = {expected_elements!r}

        assert markdown_input, f"Test {{test_id}}: Markdown input should not be empty"
        assert len(markdown_input) > 3, f"Test {{test_id}}: Markdown input is too short"

        pdf_path = self.pdf_dir / f"test_{{test_id:03d}}_{{test_name[:20]}}.pdf"

        # Placeholder output for the generated PDF artifact.
        # Replace this section with the real Markdown2Pdf.Console execution
        # when connecting these generated tests to the full converter workflow.
        pdf_path.write_text(
            f"PDF placeholder for: {{test_name}}\\n"
            f"Markdown length: {{len(markdown_input)}} characters\\n",
            encoding="utf-8",
        )

        assert pdf_path.exists(), f"Test {{test_id}}: PDF output was not created"
        assert pdf_path.stat().st_size > 0, f"Test {{test_id}}: PDF output is empty"
'''

        return pytest_code

    def convert_all(self) -> int:
        """Convert all generated Markdown test case files into pytest files."""
        markdown_files = sorted(self.markdown_dir.glob("tests_*.md"))

        if not markdown_files:
            print(f"No generated test files found in {self.markdown_dir}")
            return 0

        print(f"Converting {len(markdown_files)} file(s)...\n")

        total_tests = 0

        for filepath in markdown_files:
            print(f"Converting: {filepath.name}")

            markdown_content = filepath.read_text(encoding="utf-8", errors="ignore")
            tests = self.parse_markdown_tests(markdown_content)

            if not tests:
                print("  No valid test cases found\n")
                continue

            pytest_code = self.generate_pytest_file(tests, filepath.stem)

            output_path = self.output_dir / f"test_{filepath.stem}.py"
            output_path.write_text(pytest_code, encoding="utf-8")

            total_tests += len(tests)
            print(f"  Created: {output_path.name} ({len(tests)} tests)\n")

        return total_tests


def main() -> None:
    print("=" * 60)
    print("Converting Markdown Test Descriptions to Pytest Files")
    print("=" * 60)
    print()

    converter = MarkdownToPdfTestConverter()
    total_tests = converter.convert_all()

    if total_tests > 0:
        print("\nConversion complete.")
        print(f"  Generated tests: {total_tests}")
        print("  Test folder: tests/generated_pdf_tests/")
        print("  Placeholder PDF folder: data/generated_pdfs/")
        print("  Next command: pytest tests/generated_pdf_tests/ -v")
    else:
        print("\nNo tests were converted.")


if __name__ == "__main__":
    main()